dogs = ["Beagle","Bokser","Poedel","Pug"]
print(dogs)
dogs.append("Chihuahua")
print(dogs)
dogs.insert(3,"Golden Retriever")
dogs.append("Duitse Herder")
dogs.append("Huski")
dogs.append("Bulldog")
print(dogs)
dogs.pop(8)
print(dogs)
dogs.remove("Duitse Herder")
print(dogs)
dogs.sort()
print(dogs)
dogs.reverse()
print(dogs)